weather_weights = {
    1: {"Sunny", "Drizzle", "Cloudy", "Clear"},
    0.8: {
        "Rain Shower",
        "Overcast",
        "Haze, Mist",
        "Haze",
    },
    0.6: {
        "Shower In Vicinity, Rain Shower",
        "Shower In Vicinity, Rain",
        "Shower In Vicinity, Light Snow Shower",
        "Shower In Vicinity, Light Rain And Snow Shower",
        "Shower In Vicinity, Light Drizzle And Rain",
        "Shower In Vicinity, Heavy Rain Shower",
        "Shower In Vicinity",
        "Shallow Fog, Mist",
        "Shallow Fog",
        "Rain, Rain Shower",
        "Rain, Mist",
        "Rain, Light Rain",
        "Rain Shower, Light Rain Shower",
        "Rain And Snow Shower",
        "Rain",
        "Patchy snow possible",
        "Patchy sleet possible",
        "Patchy rain possible",
        "Patchy moderate snow",
        "Patchy light snow",
        "Patchy light rain with thunder",
        "Patchy light rain",
        "Patchy light drizzle",
        "Patchy heavy snow",
        "Patches Of Fog",
        "Partly cloudy",
        "Parftial Fog, Mist",
        "Mist, Shallow Fog",
        "Mist, Rain Shower",
        "Mist, Rain",
        "Mist, Patches Of Fog",
        "Mist, Parftial Fog",
        "Mist, Light Rain",
        "Mist, Haze",
        "Mist, Freezing Fog",
        "Mist",
        "Light snow showers",
        "Light Snow Shower",
        "Light Snow",
        "Light sleet showers",
        "Light sleet",
        "Light Rain, Rain Shower",
        "Light Rain, Rain",
        "Light Rain, Mist, Heavy Rain",
        "Light Rain, Mist",
        "Light Rain, Light Rain And Snow",
        "Light Rain, Light Drizzle And Rain",
        "Light Rain, Heavy Rain Shower",
        "Light Rain, Heavy Rain",
        "Light Rain, Drizzle And Rain",
        "Light Rain, Drizzle",
        "Light Rain With Thunderstorm, Heavy Rain With Thunderstorm",
        "Light Rain With Thunderstorm",
        "Light Rain Shower, Shower In Vicinity",
        "Light Rain Shower, Rain Shower",
        "Light Rain Shower, Heavy Rain With Thunderstorm",
        "Light Rain Shower, Heavy Rain Shower",
        "Light rain shower",
        "Light Rain And Snow, Light Rain And Snow Shower",
        "Light Rain And Snow Shower, Rain And Snow Shower",
        "Light Rain And Snow",
        "Light rain",
        "Light Drizzle, Mist, Drizzle",
        "Light Drizzle, Mist",
        "Light Drizzle, Light Rain",
        "Light Drizzle, Light Drizzle And Rain",
        "Light Drizzle, Drizzle And Rain",
        "Light Drizzle, Drizzle",
        "Light Drizzle And Rain, Rain",
        "Light Drizzle And Rain, Mist",
        "Light Drizzle And Rain, Light Rain",
        "Light Drizzle And Rain, Light Drizzle",
        "Light Drizzle And Rain, Heavy Rain",
        "Light Drizzle And Rain, Fog",
        "Light Drizzle And Rain, Drizzle And Rain, Mist",
        "Light Drizzle And Rain, Drizzle And Rain",
        "Light Drizzle And Rain",
        "Light drizzle",
        "Haze, Drizzle And Rain",
        "Fog, Mist",
        "Fog In Vicinity, Mist",
        "Fog",
        "Drizzle, Mist, Light Drizzle",
        "Drizzle, Light Rain",
        "Drizzle, Light Drizzle And Rain",
        "Drizzle, Light Drizzle",
        "Drizzle, Drizzle And Rain",
        "Drizzle And Rain, Rain",
        "Drizzle And Rain, Mist",
        "Drizzle And Rain, Light Rain",
        "Drizzle And Rain, Light Drizzle And Rain",
        "Drizzle And Rain, Light Drizzle",
        "Drizzle And Rain",
    },
    0.4: {
        "Heavy Drizzle",
        "Parftial Fog, Freezing Fog",
        "Moderate rain at times",
        "Moderate rain",
        "Moderate or heavy snow showers",
        "Moderate or heavy sleet",
        "Moderate or heavy rain with thunder",
        "Moderate or heavy rain shower",
        "Freezing Fog, Mist",
        "Freezing fog",
    },
    0.2: {
        "Rain, Heavy Rain",
        "Rain Shower, Heavy Rain Shower",
        "Moderate snow",
        "Heavy snow",
        "Heavy Rain, Rain",
        "Heavy Rain With Thunderstorm, Rain With Thunderstorm",
        "Heavy Rain With Thunderstorm",
        "Heavy Rain Shower, Thunderstorm In Vicinity, Rain Shower",
        "Heavy Rain Shower, Rain Shower",
        "Heavy Rain Shower",
        "Heavy rain at times",
        "Heavy Rain",
    },
    0: {
        "Unknown Precipitation",
        "Torrential rain shower",
        "Thundery outbreaks possible",
        "Thunderstorm, Shower In Vicinity, Small Hail/Snow Pallets With Thunderstorm",
        "Thunderstorm In Vicinity, Light Rain Shower, Heavy Rain With Thunderstorm",
        "Thunderstorm In Vicinity, Heavy Rain With Thunderstorm",
        "Thunderstorm In Vicinity, Heavy Rain Shower",
        "Thunderstorm In Vicinity",
        "Thunderstorm",
        "Rain With Thunderstorm, Heavy Rain With Thunderstorm",
        "Rain With Thunderstorm",
        "Rain Shower, Rain With Thunderstorm",
        "Blowing snow",
        "Blizzard",
    },
}
